version: "3"

services:
    asterisk:
        image: asterisk-dev-dc:asterisk-host-13
        build:
            context: .
            dockerfile: Dockerfile.asterisk
        volumes:
            - ./asterisk:/etc/asterisk
        networks:
            main:
                aliases:
                    - asterisk

    sipp_uac:
        image: sipp-dev-dc:sipp
        build:
            context: .
            dockerfile: Dockerfile.sipp
        volumes:
            - ./sipp_uac:/opt
        networks:
            main:
                aliases:
                    - sipp_uac

    sipp_uas1:
        image: sipp-dev-dc:sipp
        build:
            context: .
            dockerfile: Dockerfile.sipp
        volumes:
            - ./sipp_uac:/opt
        networks:
            main:
                aliases:
                    - sipp_uas1

    sipp_uas2:
        image: sipp-dev-dc:sipp
        build:
            context: .
            dockerfile: Dockerfile.sipp
        volumes:
            - ./sipp_uac:/opt
        networks:
            main:
                aliases:
                    - sipp_uas2

networks:
  main: