version: "3"


  sipp:
    image: sipp-dev-dc:loop-protection-asterisk
    build:
      context: .
      dockerfile: Dockerfile.sipp
    volumes:
      - ./sipp:/opt
    networks:
      main:
        aliases:
          - sipp

  asterisk:
    image: asterisk-dev-dc:loop-protection-asterisk
    build:
      context: .
      dockerfile: Dockerfile.asterisk
    networks:
      main:
        aliases:
          - asterisk
    volumes:
      - ./asterisk:/etc/asterisk

networks:
  main: